In [24]:
import numpy as np
import numpy.linalg as linalg

In [27]:
y = np.array([-100, -90, -76, -52, -12, 50], dtype=float)
y

array([-100.,  -90.,  -76.,  -52.,  -12.,   50.])

In [28]:
X = np.zeros((6,3))
for x in range(6):
    X[x, :] = [x**2, x, 1]
X

array([[ 0.,  0.,  1.],
       [ 1.,  1.,  1.],
       [ 4.,  2.,  1.],
       [ 9.,  3.,  1.],
       [16.,  4.,  1.],
       [25.,  5.,  1.]])

In [29]:
linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

array([  6.5,  -3.7, -97. ])

### a = 6.5; b = -3.7; c = -97