In [94]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

### Матрица А

In [95]:
A = np.array([3,7,5,2]).reshape((2,2))
A

array([[3, 7],
       [5, 2]])

In [96]:
D = np.zeros_like(A, dtype=float)

In [97]:
U, D[np.diag_indices(2)], V = np.linalg.svd(A)

In [98]:
U.dot(D).dot(V)

array([[3., 7.],
       [5., 2.]])

In [99]:
print(U)
print(D)
print(V)

[[-0.85 -0.53]
 [-0.53  0.85]]
[[8.71 0.  ]
 [0.   3.33]]
[[-0.59 -0.8 ]
 [ 0.8  -0.59]]


### Матрица В

In [100]:
B = np.array([0,1,3,2,3,1,0,1,0]).reshape((3,3))
B

array([[0, 1, 3],
       [2, 3, 1],
       [0, 1, 0]])

In [101]:
D = np.zeros_like(B, dtype=float)

In [102]:
U, D[np.diag_indices(3)], V = np.linalg.svd(B)

In [103]:
U.dot(D).dot(V)

array([[0., 1., 3.],
       [2., 3., 1.],
       [0., 1., 0.]])

In [104]:
print(U)
print(D)
print(V)

[[-0.57  0.82  0.04]
 [-0.81 -0.54 -0.23]
 [-0.17 -0.17  0.97]]
[[4.34 0.   0.  ]
 [0.   2.42 0.  ]
 [0.   0.   0.57]]
[[-0.37 -0.73 -0.58]
 [-0.45 -0.4   0.8 ]
 [-0.81  0.56 -0.18]]


### Матрица С

In [105]:
C = np.array([5,7,6,4,2,1,3,4,1,3,3,4,5,4,1]).reshape((5,3))
C

array([[5, 7, 6],
       [4, 2, 1],
       [3, 4, 1],
       [3, 3, 4],
       [5, 4, 1]])

In [106]:
D = np.zeros_like(C, dtype=float)

In [107]:
U, D[np.diag_indices(3)], V = np.linalg.svd(C)

In [108]:
U.dot(D).dot(V)

array([[5., 7., 6.],
       [4., 2., 1.],
       [3., 4., 1.],
       [3., 3., 4.],
       [5., 4., 1.]])

In [109]:
print(U)
print(D)
print(V)

[[-0.7  -0.47 -0.21 -0.49 -0.03]
 [-0.28  0.44  0.58 -0.23 -0.58]
 [-0.33  0.29 -0.61  0.49 -0.43]
 [-0.38 -0.37  0.49  0.68  0.13]
 [-0.41  0.61  0.01 -0.03  0.68]]
[[14.71  0.    0.  ]
 [ 0.    3.69  0.  ]
 [ 0.    0.    1.71]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]]
[[-0.6  -0.65 -0.46]
 [ 0.6   0.02 -0.8 ]
 [ 0.53 -0.76  0.38]]
